"""Section 5.2: how much a reading moves when a record is scored again. Writes data/numbers_consistency.tex.

Same judge: the PostTrainBench records scored twice by GLM-5.3 from an empty call log (common.same_judge_pairs).
Other judge: 12 Chip-Bench records scored under GPT-5.6-sol and under GLM-5.3.
Reported: the median absolute difference over all dimensions E1-E3 and T1-T6 (E4 is checked against labels in 5.1).
Usage: python paper/data/make_consistency_numbers.py   (OEB_DATA = the extracted dataset)
"""
import json, glob, os, statistics as st
from pathlib import Path
from common import official_cheat, same_judge_pairs
HERE = Path(__file__).resolve().parent
ROOT = Path(os.environ.get("OEB_DATA", ".")); PT = ROOT / "out/posttrainbench"
DIMS = ["E1", "E2", "E3", "T1", "T2", "T3", "T4", "T5", "T6"]
num = lambda v: isinstance(v, (int, float))
def M(u): return json.load(open(Path(u) / "measure.json"))["dimensions"]
def diffs(pairs):
    out = []
    for a, c in pairs:
        if not ((Path(a) / "measure.json").exists() and (Path(c) / "measure.json").exists()): continue
        x, y = M(a), M(c)
        out += [abs(x[d]["score"] - y[d]["score"]) for d in DIMS if num(x[d]["score"]) and num(y[d]["score"])]
    return out
same = same_judge_pairs(PT)
other = [(ROOT / "out/chipbench/hc47-sol" / Path(f).parent.name, Path(f).parent) for f in sorted(glob.glob(str(ROOT / "out/chipbench/hc47-glm/*/measure.json")))]
other = [p for p in other if (Path(p[0]) / "measure.json").exists()]
def rates(u, part):
    """(dimension, construct) -> its numerator (part "k") or denominator (part "n"), for the rate-valued constructs
    of E1-E3 and T2-T6."""
    out = {}
    for d, v in M(u).items():
        if d in DIMS and d != "T1":
            for c, x in ((v or {}).get("constructs") or {}).items():
                if isinstance(x, dict) and num(x.get("k")) and num(x.get("n")): out[(d, c)] = x[part]
    return out
def kdiffs(pairs):
    out = []
    for a, c in pairs:
        if not ((Path(a) / "measure.json").exists() and (Path(c) / "measure.json").exists()): continue
        x, y = rates(a, "k"), rates(c, "k"); out += [abs(x[k] - y[k]) for k in x.keys() & y.keys()]
    return out
flag = lambda u: M(u)["E4"]["score"] < 1
cheat = [(a, c) for a, c in same if official_cheat(a)]
Mc = {"conSameMedian": f"{st.median(diffs(same)):.2f}", "conOtherMedian": f"{st.median(diffs(other)):.2f}", "nConSame": len(same), "nConOther": len(other),
      "nCheatTwice": len(cheat), "nCheatTwiceFlagged": sum(flag(a) and flag(c) for a, c in cheat),
      "nCheatTwiceMissed": sum(not flag(a) and not flag(c) for a, c in cheat), "conSameCount": f"{st.median(kdiffs(same)):.0f}", "conOtherCount": f"{st.median(kdiffs(other)):.0f}"}
per = {}
for a, c in same:
    if (Path(a) / "measure.json").exists() and (Path(c) / "measure.json").exists():
        for k, n in rates(a, "n").items(): per.setdefault(k, []).append(n)
Mc["conSameDenomMax"] = f"{max(st.median(v) for v in per.values()):.0f}"   # the construct with the most opportunities: its median per run
(HERE / "numbers_consistency.tex").write_text("% generated by paper/data/make_consistency_numbers.py -- do not edit by hand\n" + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in Mc.items()))
print(Mc)
