"""Section 6.4 ("The persona comes with the model"): how much of each reading follows the model, how much the task.

Writes data/numbers_persona.tex, data/numbers_persona.json and tables/persona.tex, from every scored PostTrainBench
run.

Two-way decomposition of variance without interaction: reading ~ model + task, fitted by least squares on the
runs where the reading is defined. The share reported for a factor is the sum of squares it explains when it is
entered AFTER the other factor (so nothing is credited twice; the design is unbalanced), divided by the total sum
of squares. Model = the agent configuration (a second run of the same configuration counts as the same model);
task = the PostTrainBench panel. Usage, from the repo root: python paper/data/make_persona_numbers.py
"""
import json, glob, os
from pathlib import Path
import numpy as np
ROOT = Path(os.environ.get("OEB_DATA", ".")); HERE = Path(__file__).resolve().parent
PAN = {"AIME 2025": "aime2-w5-merge-glm53", "Arena-Hard Writing": "arenahard-gemma-w5-glm53", "BFCL": "bfcl-gemma-w5-glm53",
       "HealthBench": "healthbench-gemma-w5-glm53", "HumanEval": "humaneval-gemma-w5-glm53", "GPQA": "gpqa-gemma-w5-glm53"}
DIMS = ["T1", "T2", "T3", "T4", "T5", "T6", "E1", "E2", "E3", "E4"]
rows = []
for task, b in PAN.items():
    for u in sorted(glob.glob(str(ROOT / "out/posttrainbench" / b / "*/measure.json"))):
        name = os.path.basename(os.path.dirname(u)); model = name[:-3] if name.endswith("-r2") else name
        d = json.load(open(u))["dimensions"]
        rows.append(dict(task=task, model=model, **{k: (d.get(k) or {}).get("score") for k in DIMS}))

def ss_after(y, first, second):
    """Sum of squares explained by `second` when entered after `first` (dummy-coded, intercept included)."""
    def X(*facs):
        cols = [np.ones(len(y))]
        for f in facs:
            lv = sorted(set(f))[1:]                       # drop one level per factor
            cols += [np.array([1.0 if v == l else 0.0 for v in f]) for l in lv]
        return np.column_stack(cols)
    def rss(M):
        beta, *_ = np.linalg.lstsq(M, y, rcond=None); return float(np.sum((y - M @ beta) ** 2))
    return rss(X(first)) - rss(X(first, second))

# Chance level: a factor with many levels explains some variance by luck, and there are more models than tasks. The
# share a factor would explain if its labels were shuffled (mean of 200 shuffles) is reported next to the real share.
rng = np.random.default_rng(0)
out = {}
for k in DIMS:
    rs = [r for r in rows if isinstance(r[k], (int, float))]
    y = np.array([r[k] for r in rs]); models = [r["model"] for r in rs]; tasks = [r["task"] for r in rs]
    tot = float(np.sum((y - y.mean()) ** 2))
    if len(rs) < 10 or tot == 0: out[k] = None; continue
    nm = [ss_after(y, tasks, list(rng.permutation(models))) / tot for _ in range(200)]
    nt = [ss_after(y, models, list(rng.permutation(tasks))) / tot for _ in range(200)]
    out[k] = dict(runs=len(rs), models=len(set(models)), tasks=len(set(tasks)),
                  model=ss_after(y, tasks, models) / tot, task=ss_after(y, models, tasks) / tot,
                  model_chance=float(np.mean(nm)), task_chance=float(np.mean(nt)))
W = {"1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five", "6": "Six"}
name = lambda k: k[0] + W[k[1]]   # LaTeX macro names cannot hold digits: T1 -> TOne
macros = {"nPersonaRuns": len(rows), "nPersonaModels": len({r["model"] for r in rows})}
for k, v in out.items():
    if v:
        macros[f"var{name(k)}Model"] = f"{100 * v['model']:.0f}"; macros[f"var{name(k)}Task"] = f"{100 * v['task']:.0f}"; macros[f"var{name(k)}Runs"] = v["runs"]
        macros[f"var{name(k)}ModelChance"] = f"{100 * v['model_chance']:.0f}"; macros[f"var{name(k)}TaskChance"] = f"{100 * v['task_chance']:.0f}"
TR = [out[f"T{i}"] for i in range(1, 7) if out.get(f"T{i}")]
macros.update(varTraitModelMin=f"{100 * min(v['model'] for v in TR):.0f}", varTraitModelMax=f"{100 * max(v['model'] for v in TR):.0f}",
              varTraitTaskMin=f"{100 * min(v['task'] for v in TR):.0f}", varTraitTaskMax=f"{100 * max(v['task'] for v in TR):.0f}",
              varTraitModelMedian=f"{100 * np.median([v['model'] for v in TR]):.0f}", varTraitTaskMedian=f"{100 * np.median([v['task'] for v in TR]):.0f}")
(HERE / "numbers_persona.tex").write_text("% generated by paper/data/make_persona_numbers.py -- do not edit by hand\n"
    + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in macros.items()))
# Table (Section 6.4), one row per persona trait: the share of its variance over the PostTrainBench runs that the
# model explains, that the task explains, and the model's share by chance; then each core model's mean score
NAMES = {"T1": "T1 budget", "T2": "T2 concurrency", "T3": "T3 search", "T4": "T4 failure style", "T5": "T5 provenance", "T6": "T6 tempo"}
PROFILE = [("opus5", "Opus 5"), ("fable5", "Fable 5"), ("gpt56", "GPT-5.6"), ("gpt55", "GPT-5.5"), ("kimik3", "Kimi K3"), ("glm52", "GLM-5.2")]
L = [r"\begin{tabular}{@{}lccc@{\hspace{14pt}}cccccc@{}}", r"\toprule",
     r" & \multicolumn{3}{c}{\textbf{Variance explained by}} & \multicolumn{6}{c}{\textbf{Mean score of each model}} \\",
     r"\cmidrule(lr){2-4}\cmidrule(l){5-10}",
     r"\textbf{Trait} & \textbf{model} & \textbf{task} & \textbf{chance} & " + " & ".join(rf"\textbf{{{lab}}}" for _, lab in PROFILE) + r" \\", r"\midrule"]
for k in ("T1", "T2", "T3", "T4", "T5", "T6"):
    v = out[k]; cells = []
    for key, _ in PROFILE:
        xs = [r[k] for r in rows if r["model"] == key and r[k] is not None]
        cells.append(f"{sum(xs) / len(xs):.2f}".replace("0.", ".", 1) if len(xs) >= 3 else "--")   # fewer than 3 runs: too few, as in the figure
    L.append(f"{NAMES[k]} & \\textbf{{{100 * v['model']:.0f}\\%}} & {100 * v['task']:.0f}\\% & {100 * v['model_chance']:.0f}\\% & " + " & ".join(cells) + r" \\")
L += [r"\bottomrule", r"\end{tabular}"]
(HERE.parent / "tables/persona.tex").write_text("\n".join(L) + "\n")
(HERE / "numbers_persona.json").write_text(json.dumps(out, indent=1))
print(len(rows), "runs,", len({r["model"] for r in rows}), "models")
for k, v in out.items():
    print(k, "--" if not v else f"model {100*v['model']:5.1f}% (chance {100*v['model_chance']:4.1f}%)  task {100*v['task']:5.1f}% (chance {100*v['task_chance']:4.1f}%)  (n={v['runs']}, {v['models']} models, {v['tasks']} tasks)")
